version: '3.9'

services:
  mysql:
    image: mysql:8.0.29
    container_name : project-mysql
    environment:
      MYSQL_USER: 'PROJECT'
      MYSQL_DATABASE: 'PROJECT'
      MYSQL_PASSWORD: 'PROJECT'
      MYSQL_ROOT_PASSWORD: 'ROOT'
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    restart : unless-stopped    
    volumes:
      - ./context-files/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 10s
      retries: 10
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --skip-character-set-client-handshake      
      
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-etl-pipeline:v1.1.0
    container_name : python-etl-pipeline
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./python-etl-pipeline:/app
    command: ["sleep", "60000"]